
/*
 *    MCreator note: This file will be REGENERATED on each build.
 */
package net.mcreator.ufd.init;

import net.minecraftforge.registries.RegistryObject;
import net.minecraftforge.registries.ForgeRegistries;
import net.minecraftforge.registries.DeferredRegister;
import net.minecraftforge.common.ForgeSpawnEggItem;

import net.minecraft.world.level.block.Block;
import net.minecraft.world.item.Item;
import net.minecraft.world.item.BlockItem;

import net.mcreator.ufd.item.VampirebladeItem;
import net.mcreator.ufd.item.TruewoodenswordItem;
import net.mcreator.ufd.item.TrasherItem;
import net.mcreator.ufd.item.ThundertridentItem;
import net.mcreator.ufd.item.ThunderstoneItem;
import net.mcreator.ufd.item.ThestarofinfinitespaceItem;
import net.mcreator.ufd.item.ThedestroyerofnatureItem;
import net.mcreator.ufd.item.ThecoreofadyingstarItem;
import net.mcreator.ufd.item.StrawberryItem;
import net.mcreator.ufd.item.StonegthswordItem;
import net.mcreator.ufd.item.StonegthshovelItem;
import net.mcreator.ufd.item.StonegthhammerItem;
import net.mcreator.ufd.item.StonegthItem;
import net.mcreator.ufd.item.StickstonegthItem;
import net.mcreator.ufd.item.SplinterlosfoliteItem;
import net.mcreator.ufd.item.SparklingswordItem;
import net.mcreator.ufd.item.SandwichItem;
import net.mcreator.ufd.item.RedstonestickItem;
import net.mcreator.ufd.item.RaspberryItem;
import net.mcreator.ufd.item.OldredstounsworldItem;
import net.mcreator.ufd.item.OldredstounshovelItem;
import net.mcreator.ufd.item.OldredstounhammerItem;
import net.mcreator.ufd.item.OldredstounItem;
import net.mcreator.ufd.item.MetaloftheancientsItem;
import net.mcreator.ufd.item.LosfoliteswordItem;
import net.mcreator.ufd.item.LosfoliteshovelItem;
import net.mcreator.ufd.item.LosfolitepickaxeItem;
import net.mcreator.ufd.item.LosfoliteingotItem;
import net.mcreator.ufd.item.LosfoliteberryItem;
import net.mcreator.ufd.item.LavastoneItem;
import net.mcreator.ufd.item.KatanaofDeathItem;
import net.mcreator.ufd.item.InfernalswordItem;
import net.mcreator.ufd.item.InfernalmetalItem;
import net.mcreator.ufd.item.InfernalhammerItem;
import net.mcreator.ufd.item.HeavenlyswordItem;
import net.mcreator.ufd.item.HeavenlymetalItem;
import net.mcreator.ufd.item.HeavenlyhammerItem;
import net.mcreator.ufd.item.HeartentItem;
import net.mcreator.ufd.item.GalaxyCutterItem;
import net.mcreator.ufd.item.FlowerswordItem;
import net.mcreator.ufd.item.FlowershovelItem;
import net.mcreator.ufd.item.FlowerpickaxeItem;
import net.mcreator.ufd.item.FloweraxeItem;
import net.mcreator.ufd.item.FanofcelestialstarsItem;
import net.mcreator.ufd.item.EdiblerootsItem;
import net.mcreator.ufd.item.DuhatItem;
import net.mcreator.ufd.item.DarkmetalswordItem;
import net.mcreator.ufd.item.DarkmetalshovelItem;
import net.mcreator.ufd.item.DarkmetalingotItem;
import net.mcreator.ufd.item.DarkmetalhamerItem;
import net.mcreator.ufd.item.CurrantItem;
import net.mcreator.ufd.item.ConcertoftheancientsItem;
import net.mcreator.ufd.item.CherryItem;
import net.mcreator.ufd.item.ChargedmetaloftheancientsItem;
import net.mcreator.ufd.item.BoiledediblerootsItem;
import net.mcreator.ufd.item.BluestrengthswordItem;
import net.mcreator.ufd.item.BluestrengthshovelItem;
import net.mcreator.ufd.item.BluestrengthhammerItem;
import net.mcreator.ufd.item.BluestrenghtItem;
import net.mcreator.ufd.item.BlueberriesItem;
import net.mcreator.ufd.item.BloodyfragmentItem;
import net.mcreator.ufd.item.BlackberryItem;
import net.mcreator.ufd.item.BerrysaladItem;
import net.mcreator.ufd.item.AncientworldItem;
import net.mcreator.ufd.item.AncientCoinItem;
import net.mcreator.ufd.item.AbyssItem;
import net.mcreator.ufd.HotaMod;

public class HotaModItems {
	public static final DeferredRegister<Item> REGISTRY = DeferredRegister.create(ForgeRegistries.ITEMS, HotaMod.MODID);
	public static final RegistryObject<Item> DARKMETALINGOT = REGISTRY.register("darkmetalingot", () -> new DarkmetalingotItem());
	public static final RegistryObject<Item> DARKMETALSWORD = REGISTRY.register("darkmetalsword", () -> new DarkmetalswordItem());
	public static final RegistryObject<Item> DARKMETALSHOVEL = REGISTRY.register("darkmetalshovel", () -> new DarkmetalshovelItem());
	public static final RegistryObject<Item> DARKMETALHAMER = REGISTRY.register("darkmetalhamer", () -> new DarkmetalhamerItem());
	public static final RegistryObject<Item> OLDREDSTOUN = REGISTRY.register("oldredstoun", () -> new OldredstounItem());
	public static final RegistryObject<Item> OLDREDSTOUNSWORLD = REGISTRY.register("oldredstounsworld", () -> new OldredstounsworldItem());
	public static final RegistryObject<Item> OLDREDSTOUNSHOVEL = REGISTRY.register("oldredstounshovel", () -> new OldredstounshovelItem());
	public static final RegistryObject<Item> OLDREDSTOUNHAMMER = REGISTRY.register("oldredstounhammer", () -> new OldredstounhammerItem());
	public static final RegistryObject<Item> BLUESTRENGHT = REGISTRY.register("bluestrenght", () -> new BluestrenghtItem());
	public static final RegistryObject<Item> BLUESTRENGTHSWORD = REGISTRY.register("bluestrengthsword", () -> new BluestrengthswordItem());
	public static final RegistryObject<Item> BLUESTRENGTHSHOVEL = REGISTRY.register("bluestrengthshovel", () -> new BluestrengthshovelItem());
	public static final RegistryObject<Item> BLUESTRENGTHHAMMER = REGISTRY.register("bluestrengthhammer", () -> new BluestrengthhammerItem());
	public static final RegistryObject<Item> STONEGTH = REGISTRY.register("stonegth", () -> new StonegthItem());
	public static final RegistryObject<Item> STICKSTONEGTH = REGISTRY.register("stickstonegth", () -> new StickstonegthItem());
	public static final RegistryObject<Item> STONEGTHHAMMER = REGISTRY.register("stonegthhammer", () -> new StonegthhammerItem());
	public static final RegistryObject<Item> STONEGTHSWORD = REGISTRY.register("stonegthsword", () -> new StonegthswordItem());
	public static final RegistryObject<Item> STONEGTHSHOVEL = REGISTRY.register("stonegthshovel", () -> new StonegthshovelItem());
	public static final RegistryObject<Item> HEAVENLYMETAL = REGISTRY.register("heavenlymetal", () -> new HeavenlymetalItem());
	public static final RegistryObject<Item> HEAVENLYSWORD = REGISTRY.register("heavenlysword", () -> new HeavenlyswordItem());
	public static final RegistryObject<Item> HEAVENLYHAMMER = REGISTRY.register("heavenlyhammer", () -> new HeavenlyhammerItem());
	public static final RegistryObject<Item> INFERNALMETAL = REGISTRY.register("infernalmetal", () -> new InfernalmetalItem());
	public static final RegistryObject<Item> INFERNALSWORD = REGISTRY.register("infernalsword", () -> new InfernalswordItem());
	public static final RegistryObject<Item> INFERNALHAMMER = REGISTRY.register("infernalhammer", () -> new InfernalhammerItem());
	public static final RegistryObject<Item> FLOWERSWORD = REGISTRY.register("flowersword", () -> new FlowerswordItem());
	public static final RegistryObject<Item> FLOWERSHOVEL = REGISTRY.register("flowershovel", () -> new FlowershovelItem());
	public static final RegistryObject<Item> FLOWERPICKAXE = REGISTRY.register("flowerpickaxe", () -> new FlowerpickaxeItem());
	public static final RegistryObject<Item> FLOWERAXE = REGISTRY.register("floweraxe", () -> new FloweraxeItem());
	public static final RegistryObject<Item> CONCERTOFTHEANCIENTS = REGISTRY.register("concertoftheancients", () -> new ConcertoftheancientsItem());
	public static final RegistryObject<Item> RUSTYMETAL = block(HotaModBlocks.RUSTYMETAL);
	public static final RegistryObject<Item> RUSTYMETAL_2 = block(HotaModBlocks.RUSTYMETAL_2);
	public static final RegistryObject<Item> VAMPIREBLADE = REGISTRY.register("vampireblade", () -> new VampirebladeItem());
	public static final RegistryObject<Item> KATANAOF_DEATH = REGISTRY.register("katanaof_death", () -> new KatanaofDeathItem());
	public static final RegistryObject<Item> METALOFTHEANCIENTS = REGISTRY.register("metaloftheancients", () -> new MetaloftheancientsItem());
	public static final RegistryObject<Item> CHARGEDMETALOFTHEANCIENTS = REGISTRY.register("chargedmetaloftheancients", () -> new ChargedmetaloftheancientsItem());
	public static final RegistryObject<Item> FANOFCELESTIALSTARS = REGISTRY.register("fanofcelestialstars", () -> new FanofcelestialstarsItem());
	public static final RegistryObject<Item> THECOREOFADYINGSTAR = REGISTRY.register("thecoreofadyingstar", () -> new ThecoreofadyingstarItem());
	public static final RegistryObject<Item> THESTAROFINFINITESPACE = REGISTRY.register("thestarofinfinitespace", () -> new ThestarofinfinitespaceItem());
	public static final RegistryObject<Item> STRAWBERRY = REGISTRY.register("strawberry", () -> new StrawberryItem());
	public static final RegistryObject<Item> RASPBERRY = REGISTRY.register("raspberry", () -> new RaspberryItem());
	public static final RegistryObject<Item> BLACKBERRY = REGISTRY.register("blackberry", () -> new BlackberryItem());
	public static final RegistryObject<Item> CHERRY = REGISTRY.register("cherry", () -> new CherryItem());
	public static final RegistryObject<Item> BLUEBERRIES = REGISTRY.register("blueberries", () -> new BlueberriesItem());
	public static final RegistryObject<Item> CURRANT = REGISTRY.register("currant", () -> new CurrantItem());
	public static final RegistryObject<Item> BERRYSALAD = REGISTRY.register("berrysalad", () -> new BerrysaladItem());
	public static final RegistryObject<Item> EYE_SPAWN_EGG = REGISTRY.register("eye_spawn_egg", () -> new ForgeSpawnEggItem(HotaModEntities.EYE, -1, -65536, new Item.Properties()));
	public static final RegistryObject<Item> THEDARKMONK_SPAWN_EGG = REGISTRY.register("thedarkmonk_spawn_egg", () -> new ForgeSpawnEggItem(HotaModEntities.THEDARKMONK, -11655424, -14413312, new Item.Properties()));
	public static final RegistryObject<Item> MECHANICALEYE_SPAWN_EGG = REGISTRY.register("mechanicaleye_spawn_egg", () -> new ForgeSpawnEggItem(HotaModEntities.MECHANICALEYE, -20663, -16711681, new Item.Properties()));
	public static final RegistryObject<Item> DUHAT = REGISTRY.register("duhat", () -> new DuhatItem());
	public static final RegistryObject<Item> CHERRYFOLIAGE = block(HotaModBlocks.CHERRYFOLIAGE);
	public static final RegistryObject<Item> ANCIENTWORLD = REGISTRY.register("ancientworld", () -> new AncientworldItem());
	public static final RegistryObject<Item> REDSTONESTICK = REGISTRY.register("redstonestick", () -> new RedstonestickItem());
	public static final RegistryObject<Item> LOSFOLITEBERRY = REGISTRY.register("losfoliteberry", () -> new LosfoliteberryItem());
	public static final RegistryObject<Item> VAMPIRE_SPAWN_EGG = REGISTRY.register("vampire_spawn_egg", () -> new ForgeSpawnEggItem(HotaModEntities.VAMPIRE, -3355444, -65536, new Item.Properties()));
	public static final RegistryObject<Item> ENT_SPAWN_EGG = REGISTRY.register("ent_spawn_egg", () -> new ForgeSpawnEggItem(HotaModEntities.ENT, -14479104, -15046144, new Item.Properties()));
	public static final RegistryObject<Item> HEARTENT = REGISTRY.register("heartent", () -> new HeartentItem());
	public static final RegistryObject<Item> SPLINTERLOSFOLITE = REGISTRY.register("splinterlosfolite", () -> new SplinterlosfoliteItem());
	public static final RegistryObject<Item> CRYSTALLOSFOLITE = block(HotaModBlocks.CRYSTALLOSFOLITE);
	public static final RegistryObject<Item> BLOODYFRAGMENT = REGISTRY.register("bloodyfragment", () -> new BloodyfragmentItem());
	public static final RegistryObject<Item> THEDESTROYEROFNATURE = REGISTRY.register("thedestroyerofnature", () -> new ThedestroyerofnatureItem());
	public static final RegistryObject<Item> SANDWICH = REGISTRY.register("sandwich", () -> new SandwichItem());
	public static final RegistryObject<Item> LOSFOLITEINGOT = REGISTRY.register("losfoliteingot", () -> new LosfoliteingotItem());
	public static final RegistryObject<Item> LOSFOLITESWORD = REGISTRY.register("losfolitesword", () -> new LosfoliteswordItem());
	public static final RegistryObject<Item> LOSFOLITEPICKAXE = REGISTRY.register("losfolitepickaxe", () -> new LosfolitepickaxeItem());
	public static final RegistryObject<Item> LOSFOLITESHOVEL = REGISTRY.register("losfoliteshovel", () -> new LosfoliteshovelItem());
	public static final RegistryObject<Item> SANDBRICKS = block(HotaModBlocks.SANDBRICKS);
	public static final RegistryObject<Item> THUNDERTRIDENT = REGISTRY.register("thundertrident", () -> new ThundertridentItem());
	public static final RegistryObject<Item> PHARAOH_SPAWN_EGG = REGISTRY.register("pharaoh_spawn_egg", () -> new ForgeSpawnEggItem(HotaModEntities.PHARAOH, -726144, -12633071, new Item.Properties()));
	public static final RegistryObject<Item> CRYSTAL_LOG = block(HotaModBlocks.CRYSTAL_LOG);
	public static final RegistryObject<Item> CRYSTAL_PLANKS = block(HotaModBlocks.CRYSTAL_PLANKS);
	public static final RegistryObject<Item> CRYSTAL_STAIRS = block(HotaModBlocks.CRYSTAL_STAIRS);
	public static final RegistryObject<Item> CRYSTAL_SLAB = block(HotaModBlocks.CRYSTAL_SLAB);
	public static final RegistryObject<Item> CRYSTAL_FENCE = block(HotaModBlocks.CRYSTAL_FENCE);
	public static final RegistryObject<Item> CRYSTAL_FENCE_GATE = block(HotaModBlocks.CRYSTAL_FENCE_GATE);
	public static final RegistryObject<Item> CRYSTAL_PRESSURE_PLATE = block(HotaModBlocks.CRYSTAL_PRESSURE_PLATE);
	public static final RegistryObject<Item> CRYSTAL_BUTTON = block(HotaModBlocks.CRYSTAL_BUTTON);
	public static final RegistryObject<Item> HOLY_WOOD = block(HotaModBlocks.HOLY_WOOD);
	public static final RegistryObject<Item> HOLY_LOG = block(HotaModBlocks.HOLY_LOG);
	public static final RegistryObject<Item> HOLY_PLANKS = block(HotaModBlocks.HOLY_PLANKS);
	public static final RegistryObject<Item> HOLY_LEAVES = block(HotaModBlocks.HOLY_LEAVES);
	public static final RegistryObject<Item> HOLY_STAIRS = block(HotaModBlocks.HOLY_STAIRS);
	public static final RegistryObject<Item> HOLY_SLAB = block(HotaModBlocks.HOLY_SLAB);
	public static final RegistryObject<Item> HOLY_FENCE = block(HotaModBlocks.HOLY_FENCE);
	public static final RegistryObject<Item> HOLY_FENCE_GATE = block(HotaModBlocks.HOLY_FENCE_GATE);
	public static final RegistryObject<Item> HOLY_PRESSURE_PLATE = block(HotaModBlocks.HOLY_PRESSURE_PLATE);
	public static final RegistryObject<Item> HOLY_BUTTON = block(HotaModBlocks.HOLY_BUTTON);
	public static final RegistryObject<Item> EDIBLEROOTS = REGISTRY.register("edibleroots", () -> new EdiblerootsItem());
	public static final RegistryObject<Item> BOILEDEDIBLEROOTS = REGISTRY.register("boilededibleroots", () -> new BoiledediblerootsItem());
	public static final RegistryObject<Item> SNOWBRICKS = block(HotaModBlocks.SNOWBRICKS);
	public static final RegistryObject<Item> ICEBRICKS = block(HotaModBlocks.ICEBRICKS);
	public static final RegistryObject<Item> CARNIVOROUSFLOWER_SPAWN_EGG = REGISTRY.register("carnivorousflower_spawn_egg", () -> new ForgeSpawnEggItem(HotaModEntities.CARNIVOROUSFLOWER, -2686976, -16099318, new Item.Properties()));
	public static final RegistryObject<Item> MOSSCOBBLESTONE = block(HotaModBlocks.MOSSCOBBLESTONE);
	public static final RegistryObject<Item> LAVASTONE = REGISTRY.register("lavastone", () -> new LavastoneItem());
	public static final RegistryObject<Item> THUNDERSTONE = REGISTRY.register("thunderstone", () -> new ThunderstoneItem());
	public static final RegistryObject<Item> MOSSPLANT = block(HotaModBlocks.MOSSPLANT);
	public static final RegistryObject<Item> MOSSYPIG_SPAWN_EGG = REGISTRY.register("mossypig_spawn_egg", () -> new ForgeSpawnEggItem(HotaModEntities.MOSSYPIG, -39220, -13408768, new Item.Properties()));
	public static final RegistryObject<Item> SWARMOFFIREFLIES_SPAWN_EGG = REGISTRY.register("swarmoffireflies_spawn_egg", () -> new ForgeSpawnEggItem(HotaModEntities.SWARMOFFIREFLIES, -13033465, -1024, new Item.Properties()));
	public static final RegistryObject<Item> VAYF = block(HotaModBlocks.VAYF);
	public static final RegistryObject<Item> XY = block(HotaModBlocks.XY);
	public static final RegistryObject<Item> PENIC = block(HotaModBlocks.PENIC);
	public static final RegistryObject<Item> JOPAMALINA = block(HotaModBlocks.JOPAMALINA);
	public static final RegistryObject<Item> LOHMALINA = block(HotaModBlocks.LOHMALINA);
	public static final RegistryObject<Item> SUKAMALINA = block(HotaModBlocks.SUKAMALINA);
	public static final RegistryObject<Item> GFDIJ = block(HotaModBlocks.GFDIJ);
	public static final RegistryObject<Item> DHSDGYCHIERNIKA = block(HotaModBlocks.DHSDGYCHIERNIKA);
	public static final RegistryObject<Item> FGDRGCHIERNIKA = block(HotaModBlocks.FGDRGCHIERNIKA);
	public static final RegistryObject<Item> RRERGHOLUBIKA = block(HotaModBlocks.RRERGHOLUBIKA);
	public static final RegistryObject<Item> FSDFGHOLUBIKA = block(HotaModBlocks.FSDFGHOLUBIKA);
	public static final RegistryObject<Item> VCVXVGHOLUBIKA = block(HotaModBlocks.VCVXVGHOLUBIKA);
	public static final RegistryObject<Item> GFDFDGIEZHIEVIKA = block(HotaModBlocks.GFDFDGIEZHIEVIKA);
	public static final RegistryObject<Item> FDSFSIEZHIEVIKA = block(HotaModBlocks.FDSFSIEZHIEVIKA);
	public static final RegistryObject<Item> SDFDFDSIEZHIEVIKA = block(HotaModBlocks.SDFDFDSIEZHIEVIKA);
	public static final RegistryObject<Item> TEST = block(HotaModBlocks.TEST);
	public static final RegistryObject<Item> ICEOLOGER_SPAWN_EGG = REGISTRY.register("iceologer_spawn_egg", () -> new ForgeSpawnEggItem(HotaModEntities.ICEOLOGER, -6710887, -13408513, new Item.Properties()));
	public static final RegistryObject<Item> TRUEWOODENSWORD = REGISTRY.register("truewoodensword", () -> new TruewoodenswordItem());
	public static final RegistryObject<Item> SPARKLINGSWORD = REGISTRY.register("sparklingsword", () -> new SparklingswordItem());
	public static final RegistryObject<Item> ABYSS = REGISTRY.register("abyss", () -> new AbyssItem());
	public static final RegistryObject<Item> TRASHER = REGISTRY.register("trasher", () -> new TrasherItem());
	public static final RegistryObject<Item> MOSSY_HORROR_SPAWN_EGG = REGISTRY.register("mossy_horror_spawn_egg", () -> new ForgeSpawnEggItem(HotaModEntities.MOSSY_HORROR, -16764160, -13421824, new Item.Properties()));
	public static final RegistryObject<Item> GALAXY_CUTTER = REGISTRY.register("galaxy_cutter", () -> new GalaxyCutterItem());
	public static final RegistryObject<Item> ANCIENT_COIN = REGISTRY.register("ancient_coin", () -> new AncientCoinItem());
	public static final RegistryObject<Item> ODDITIES_TRADER_SPAWN_EGG = REGISTRY.register("oddities_trader_spawn_egg", () -> new ForgeSpawnEggItem(HotaModEntities.ODDITIES_TRADER, -16763905, -13312, new Item.Properties()));

	private static RegistryObject<Item> block(RegistryObject<Block> block) {
		return REGISTRY.register(block.getId().getPath(), () -> new BlockItem(block.get(), new Item.Properties()));
	}
}
